use_frameworks!

platform :ios, '9.0'

target 'CustomToastView-swift_Example' do
  pod 'CustomToastView-swift', :path => '../'

  target 'CustomToastView-swift_Tests' do
    inherit! :search_paths

    
  end
end
